#!/usr/bin/env python3
"""Merge several models' statistics.json into multi-model tables and figures.

    python3 scripts/cross_model.py OUT_A OUT_B ... --dest DIR
    (each OUT_x is a per-model output directory containing statistics.json, or the JSON itself)

Writes to DIR:
  cross_model.json                   the merged per-model numbers used below
  table_main_rows.tex                Table main rows (CoWork F2P / Strict; Oracle-Spec cells \tbd) + Mean row
  table_cost_rows.tex                Table cost rows (CoWork wall-clock min / tool calls)
  table_attrib_rows.tex              Table attrib rows + Mean row
  table_ask.tex                      complete ask tabular, one value row + one rho row per model
  table_workplace.tex                workplace-basics comparison (claims honesty, deferrals, timing, rules)
  table_strata_f2p.tex               strata x model F2P (%)
  fig_cross_loss.pdf/png             stacked earliest-loss-stage shares per model
  fig_cross_acquisition.pdf/png      stacked colleague-held acquisition shares per model
  fig_cross_claims.pdf/png           claims honesty per model: failed requirements flagged open / reported done / silent
  fig_cross_outcomes.pdf/png         F2P, strict and obtained rate per model
Models keep the order given on the command line.
"""
import argparse
import json
import statistics as st
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402

sys.path.insert(0, str(Path(__file__).resolve().parent / "figures"))
from observed_style import AQUA, BLUE, FAINT, INK, MUTED, ORANGE, VIOLET, clean, configure  # noqa: E402

TBD = r"\tbd"


def f1(x):
    return "–" if x is None else f"{x:.1f}"


def tex(m):
    return m.replace("&", r"\&").replace("_", r"\_").replace("%", r"\%").replace("#", r"\#")


def mean(v):
    v = [x for x in v if x is not None]
    return st.mean(v) if v else None


def load(p):
    p = Path(p)
    p = p / "statistics.json" if p.is_dir() else p
    return json.loads(p.read_text())


def summarise(s):
    sel = s["outcomes"]["selected"]
    L, C, dc, df, qt, wr = (s["loss"], s["collaboration"], s["delivery_claims"], s["deferrals"],
                            s["question_timing"], s["workplace_rules"])
    acq = s["requirements"]["shares_pct"]
    return dict(
        model=s["model"], n=sel["n"], f2p=sel["macro_f2p_percent"], p2p=sel["macro_p2p_percent"],
        strict_pct=sel["strict_percent"], strict=sel["strict_count"],
        wall_min=s["cost"]["wall_clock_minutes_median"], tool_calls=s["cost"]["tool_calls_median"],
        loss={k: L["shares_pct"][k] for k in ("discovery", "ask", "read", "implement")}, unresolved=L["attributed"],
        acquisition=acq, obtained_rate=100 * C["obtained_rate"]["mean"] if C["obtained_rate"]["mean"] is not None else None,
        ask={m: C[m]["mean"] for m in ("ask_rate", "targeting", "gain_per_q", "followthrough", "redundancy", "unread")},
        ask_rho={m: C[m]["spearman"] for m in ("ask_rate", "targeting", "gain_per_q", "followthrough", "redundancy", "unread")},
        claims=dict(failed=dc["failed"], flagged_open_pct=dc["failed_listed_open_pct"], reported_done_pct=dc["failed_claimed_done_pct"],
                    silent_pct=(100 - (dc["failed_listed_open_pct"] or 0) - (dc["failed_claimed_done_pct"] or 0)) if dc["failed"] else None,
                    claimed_done=dc["claimed_done"], claimed_done_failed_pct=dc["claimed_done_failed_pct"],
                    broad_claimed_done_failed_pct=s["delivery_claims_broad"]["claimed_done_failed_pct"]),
        deferrals=dict(threads=df["threads"], abandoned_pct=df["abandoned_pct"], followed_disclosed_pct=df["followed_disclosed_pct"],
                       abandoned_budget_left_median=df["abandoned_budget_left_median"]),
        timing=dict(first_fifth=100 * qt["first_fifth"], after_first_edit=100 * qt["after_first_edit"],
                    first_edit_median=100 * qt["first_edit_median_fraction"] if qt["first_edit_median_fraction"] is not None else None),
        rules=dict(rule_runs=wr["rule_runs"], edited=wr["edited_existing_tests"]),
        strata={ax: {k: v["f2p"] for k, v in d.items()} for ax, d in s["strata"].items() if isinstance(d, dict)},
        premature=(s["stopping"] or {}).get("supported"),
    )


def write(path, lines):
    path.write_text("% Generated by cowork-model-report-skill/scripts/cross_model.py\n" + "\n".join(lines) + "\n")


def tables(ms, D):
    rows = [f"{tex(m['model'])} & goal-mode & {TBD} & {TBD} & {TBD} & {f1(m['f2p'])} & {f1(m['strict_pct'])} & {TBD} & {TBD} \\\\"
            for m in ms]
    rows += [r"\midrule", rf"\textit{{Mean}} & & {TBD} & {TBD} & {TBD} & {f1(mean(m['f2p'] for m in ms))} & "
             rf"{f1(mean(m['strict_pct'] for m in ms))} & {TBD} & {TBD} \\"]
    write(D / "table_main_rows.tex", rows)
    write(D / "table_cost_rows.tex", [f"{tex(m['model'])} & {TBD} & {TBD} & {TBD} & {TBD} & {m['wall_min']:.0f} & {m['tool_calls']:g} \\\\"
                                      for m in ms])
    st_ = ("discovery", "ask", "read", "implement")
    rows = [f"{tex(m['model'])} & " + " & ".join(f1(m['loss'][k]) for k in st_) + f" & {m['unresolved']} & {TBD} \\\\" for m in ms]
    rows += [r"\midrule", r"\textit{Mean} & " + " & ".join(f1(mean(m['loss'][k] for m in ms)) for k in st_) +
             f" & {f1(mean(m['unresolved'] for m in ms))} & \\\\"]
    write(D / "table_attrib_rows.tex", rows)
    order = ["ask_rate", "targeting", "gain_per_q", "followthrough", "redundancy", "unread"]
    lines = [r"\begin{tabular}{@{}llrrrrrr@{}}", r"\toprule",
             r"Model & & Ask rate & Targeting & Gain/Q & Follow-thr. & Redundancy & Unread \\", r"\midrule"]
    for i, m in enumerate(ms):
        v = [f1(100 * m["ask"][k]) if k != "gain_per_q" else f"{m['ask'][k]:.2f}" for k in order]
        r_ = [("–" if m["ask_rho"][k] is None else f"{m['ask_rho'][k]:+.2f}") for k in order]
        lines += [rf"\multirow{{2}}{{*}}{{{tex(m['model'])}}} & mean & " + " & ".join(v) + r" \\",
                  r" & $\rho$ (F2P) & " + " & ".join(r_) + r" \\"]
        if i < len(ms) - 1:
            lines.append(r"\addlinespace[2pt]")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write(D / "table_ask.tex", lines)
    lines = [r"\begin{tabular}{@{}l" + "r" * len(ms) + "@{}}", r"\toprule",
             "Measure & " + " & ".join(tex(m["model"]) for m in ms) + r" \\", r"\midrule"]
    items = [("Failed reqs flagged open (\\%)", lambda m: f1(m["claims"]["flagged_open_pct"])),
             ("Failed reqs reported done (\\%)", lambda m: f1(m["claims"]["reported_done_pct"])),
             ("Reported done that fail (\\%)", lambda m: f1(m["claims"]["claimed_done_failed_pct"])),
             ("\\quad broad reading (\\%)", lambda m: f1(m["claims"]["broad_claimed_done_failed_pct"])),
             ("Deferral threads", lambda m: str(m["deferrals"]["threads"])),
             ("\\quad never asked again (\\%)", lambda m: f1(m["deferrals"]["abandoned_pct"])),
             ("\\quad budget left when abandoned (h)", lambda m: f1(m["deferrals"]["abandoned_budget_left_median"])),
             ("Questions in first fifth (\\%)", lambda m: f1(m["timing"]["first_fifth"])),
             ("Questions after first edit (\\%)", lambda m: f1(m["timing"]["after_first_edit"])),
             ("Runs editing protected tests", lambda m: f"{m['rules']['edited']} / {m['rules']['rule_runs']}")]
    lines += [lab + " & " + " & ".join(fn(m) for m in ms) + r" \\" for lab, fn in items]
    lines += [r"\bottomrule", r"\end{tabular}"]
    write(D / "table_workplace.tex", lines)
    axes_ = [("verifier_nodes", ["<28", "28-35", ">35"]), ("edit_size", ["<1k", "1k-5k", ">5k"]),
             ("language", ["Python", "TypeScript / JavaScript", "PHP / Ruby", "Go / Rust", "C++ / C# / Java / Kotlin"]),
             ("domain", ["Web & Frontend", "Dev Tools & Compilers", "Data & Databases", "Games & Graphics", "Other"])]
    lines = [r"\begin{tabular}{@{}ll" + "r" * len(ms) + "@{}}", r"\toprule",
             "Axis & Stratum & " + " & ".join(tex(m["model"]) for m in ms) + r" \\", r"\midrule"]
    for i, (ax, keys) in enumerate(axes_):
        for j, k in enumerate(keys):
            lines.append((ax.replace("_", " ") if j == 0 else "") + " & " + tex(k) + " & " +
                         " & ".join(f1(m["strata"].get(ax, {}).get(k)) for m in ms) + r" \\")
        if i < len(axes_) - 1:
            lines.append(r"\addlinespace[2pt]")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write(D / "table_strata_f2p.tex", lines)


def save(fig, D, stem):
    fig.savefig(D / f"{stem}.pdf", metadata={"Creator": "cross_model.py", "CreationDate": None, "ModDate": None})
    fig.savefig(D / f"{stem}.png", dpi=216)
    plt.close(fig)


def stacked(ms, D, stem, title, parts, xlabel):
    n = len(ms)
    fig, ax = plt.subplots(figsize=(473 / 72, (60 + 26 * n) / 72))
    fig.subplots_adjust(left=0.2, right=0.98, top=1 - 30 / (60 + 26 * n), bottom=34 / (60 + 26 * n))
    y = np.arange(n)
    left = np.zeros(n)
    for lab, fn, color in parts:
        v = np.array([fn(m) or 0 for m in ms], dtype=float)
        ax.barh(y, v, left=left, height=0.62, color=color, edgecolor="white", linewidth=1.2, label=lab)
        for yi, (l_, vv) in enumerate(zip(left, v)):
            if vv >= 7:
                ax.text(l_ + vv / 2, yi, f"{vv:.0f}", ha="center", va="center", size=7.2, color="white", weight="bold")
        left += v
    ax.set_yticks(y, [m["model"] for m in ms], color=INK)
    ax.set_ylim(n - 0.5, -0.5)
    ax.set_xlim(0, 100)
    ax.set_xlabel(xlabel)
    clean(ax, "x")
    ax.legend(ncol=len(parts), loc="lower left", bbox_to_anchor=(0, 1.0), frameon=False, fontsize=7, handlelength=1)
    fig.text(0.01, 0.99, title, va="top", size=8.6, weight="bold", color=INK)
    save(fig, D, stem)


def figures(ms, D):
    configure()
    stacked(ms, D, "fig_cross_loss", "Earliest stage at which unresolved F2P nodes are lost",
            [("Discovery", lambda m: m["loss"]["discovery"], FAINT), ("Ask", lambda m: m["loss"]["ask"], ORANGE),
             ("Read", lambda m: m["loss"]["read"], AQUA), ("Implement", lambda m: m["loss"]["implement"], BLUE)],
            "Share of unresolved F2P nodes (%)")
    stacked(ms, D, "fig_cross_acquisition", "Colleague-held requirements by how far the agent got",
            [("Disclosed", lambda m: m["acquisition"]["obtained"], BLUE),
             ("Card raised, not disclosed", lambda m: m["acquisition"]["card_raised_not_disclosed"], ORANGE),
             ("Owner contacted, card not raised", lambda m: m["acquisition"]["owner_contacted_card_not_raised"], VIOLET),
             ("Owner never contacted", lambda m: m["acquisition"]["owner_never_contacted"], FAINT)],
            "Share of colleague-held requirements (%)")
    stacked(ms, D, "fig_cross_claims", "What the handoff said about requirements whose tests fail",
            [("Flagged open", lambda m: m["claims"]["flagged_open_pct"], VIOLET),
             ("Reported done", lambda m: m["claims"]["reported_done_pct"], ORANGE),
             ("Not mentioned", lambda m: m["claims"]["silent_pct"], FAINT)],
            "Share of failed requirements (%)")
    n = len(ms)
    fig, ax = plt.subplots(figsize=(473 / 72, 170 / 72))
    fig.subplots_adjust(left=0.08, right=0.98, top=0.8, bottom=0.2)
    x = np.arange(n)
    w = 0.26
    for i, (lab, key, c) in enumerate([("F2P (%)", "f2p", BLUE), ("Strict (%)", "strict_pct", ORANGE),
                                       ("Colleague-held obtained (%)", "obtained_rate", VIOLET)]):
        v = [m[key] or 0 for m in ms]
        ax.bar(x + (i - 1) * w, v, width=w, color=c, label=lab, zorder=3)
        for xi, vv in zip(x, v):
            ax.text(xi + (i - 1) * w, vv + 1.5, f"{vv:.0f}", ha="center", size=6.8, color=MUTED)
    ax.set_xticks(x, [m["model"] for m in ms], color=INK)
    ax.set_ylim(0, 105)
    clean(ax, "y")
    ax.legend(ncol=3, loc="lower left", bbox_to_anchor=(0, 1.02), frameon=False, fontsize=7)
    save(fig, D, "fig_cross_outcomes")


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("inputs", nargs="+")
    p.add_argument("--dest", required=True)
    a = p.parse_args()
    D = Path(a.dest)
    D.mkdir(parents=True, exist_ok=True)
    ms = [summarise(load(x)) for x in a.inputs]
    names = [m["model"] for m in ms]
    if len(set(names)) != len(names):
        raise SystemExit(f"duplicate model names {names}; rerun the per-model reports with distinct --model")
    (D / "cross_model.json").write_text(json.dumps(ms, indent=1, ensure_ascii=False, default=float) + "\n")
    tables(ms, D)
    figures(ms, D)
    print(json.dumps({"models": names, "dest": str(D)}))


if __name__ == "__main__":
    main()
