#!/usr/bin/env python3
"""Render the per-model report, LaTeX rows/tables and figures from OUT/statistics.json.

    python3 scripts/make_report.py --out OUT [--model NAME]

Writes:
  OUT/report.md          from templates/report.md.j2 (every number is a statistics.json field)
  OUT/paper_rows.tex     ready-to-paste rows for the paper's Tables main / cost / attrib / ask / strata
  OUT/tables/*.tex       complete per-model tabulars in the paper's format (outcomes, effort, ask, attrib,
                         strata, dimensions)
  OUT/figures/*.pdf      via figures/model_figures.py
"""
import json
import subprocess
import sys
from pathlib import Path

import jinja2

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from common import config  # noqa: E402

TBD = r"\tbd"
DIM_LABELS = {
    "search_strategy": "Search strategy", "decomposition_prioritization": "Decomposition/prioritization",
    "hypothesis_testing": "Hypothesis testing", "information_value": "Information value",
    "abstraction_transfer": "Abstraction/transfer", "causal_debugging": "Causal debugging",
    "feedback_adaptation": "Feedback adaptation", "information_integration": "Information integration",
    "verification_design": "Verification design", "calibration_stopping": "Calibration/stopping",
    "scope_reconstruction": "Scope reconstruction",
    "provenance_version_reconciliation": "Provenance/version reconciliation",
    "owner_question_followthrough": "Owner questions/follow-through",
    "notification_handling": "Notification handling", "evidence_to_implementation": "Evidence to implementation",
    "delivery_accountability": "Delivery accountability",
}
STRATA = dict(
    verifier_nodes=("Verifier nodes", ["<28", "28-35", ">35"], [r"$< 28$", r"$28$--$35$", r"$> 35$"]),
    edit_size=("Edit size", ["<1k", "1k-5k", ">5k"], [r"$<1$k production lines", r"$1$k--$5$k", r"$>5$k"]),
    language=("Language", ["Python", "TypeScript / JavaScript", "PHP / Ruby", "Go / Rust", "C++ / C# / Java / Kotlin"],
              ["Python", "TypeScript / JavaScript", "PHP / Ruby", "Go / Rust", r"C++ / C\# / Java / Kotlin"]),
    domain=("Domain", ["Web & Frontend", "Dev Tools & Compilers", "Data & Databases", "Games & Graphics", "Other"],
            [r"Web \& frontend", r"Dev tools \& compilers", r"Data \& databases", r"Games \& graphics", "Other domains"]))


def f1(x):
    return "–" if x is None else f"{x:.1f}"


def f2(x):
    return "–" if x is None else f"{x:.2f}"


def rho(x):
    return "–" if x is None else f"{x:+.2f}"


def pct0(x):
    return "–" if x is None else f"{x:.0f}"


def num(x):
    if x is None:
        return "–"
    if isinstance(x, float) and not x.is_integer():
        return f"{x:,.1f}" if abs(x) >= 100 else f"{x:g}"
    return f"{int(x):,}"


def tex_model(m):
    return m.replace("&", r"\&").replace("_", r"\_").replace("%", r"\%").replace("#", r"\#")


def latex(s, model):
    M = tex_model(model)
    sel = s["outcomes"]["selected"]
    L = s["loss"]
    sh = L["shares_pct"]
    c = s["collaboration"]
    order = ["ask_rate", "targeting", "gain_per_q", "followthrough", "redundancy", "unread"]
    ask_vals = [f1(100 * c[m]["mean"]) if m != "gain_per_q" else f2(c[m]["mean"]) for m in order]
    ask_rhos = [rho(c[m]["spearman"]) for m in order]
    cost = s["cost"]
    rows = {}
    rows["main"] = (f"{M} & goal-mode & {TBD} & {TBD} & {TBD} & {f1(sel['macro_f2p_percent'])} & "
                    f"{f1(sel['strict_percent'])} & {TBD} & {TBD} \\\\")
    rows["cost"] = (f"{M} & {TBD} & {TBD} & {TBD} & {TBD} & {cost['wall_clock_minutes_median']:.0f} & "
                    f"{cost['tool_calls_median']:g} \\\\")
    rows["attrib"] = (f"{M} & {f1(sh['discovery'])} & {f1(sh['ask'])} & {f1(sh['read'])} & {f1(sh['implement'])} & "
                      f"{L['attributed']} & {TBD} \\\\")
    rows["ask"] = (f"{M} (\\textsc{{CoWork}}) & " + " & ".join(ask_vals) + r" \\" + "\n" +
                   r"Spearman $\rho$ with F2P & " + " & ".join(ask_rhos) + r" \\")
    # strata: a stand-alone tabular body (one model) and a per-model column block
    body = []
    for i, (key, (axis, keys, labels)) in enumerate(STRATA.items()):
        for j, (k, lab) in enumerate(zip(keys, labels)):
            d = s["strata"][key].get(k)
            first = rf"\multirow{{{len(keys)}}}{{*}}{{{axis}}}" if j == 0 else ""
            if d:
                body.append(f" {first} & {lab} & {d['n']} & {f1(d['f2p'])} & {d['strict']} & {f1(d['obtained'])} \\\\")
            else:
                body.append(f" {first} & {lab} & 0 & – & – & – \\\\")
        if i < len(STRATA) - 1:
            body.append(r"\addlinespace[2pt]")
    rows["strata"] = "\n".join(body)
    return rows


def write_tables(s, model, rows, T):
    T.mkdir(parents=True, exist_ok=True)
    M = tex_model(model)
    head = f"% Generated by cowork-model-report-skill/scripts/make_report.py for {model}.\n"

    def tab(name, cols, header, lines):
        (T / name).write_text(head + "\n".join([rf"\begin{{tabular}}{{{cols}}}", r"\toprule"] + header +
                                               [r"\midrule"] + lines + [r"\bottomrule", r"\end{tabular}", ""]))
    o = s["outcomes"]
    lines = []
    for key, label in [("selected", "Selected runs")]:
        d = o[key]
        if d:
            lines.append(f"{label} & {d['n']} & {d['macro_f2p_percent']:.1f} & {d['macro_p2p_percent']:.1f} & "
                         f"{d['strict_percent']:.1f} ({d['strict_count']}) \\\\")
    tab("table_observed_outcomes.tex", "lrrrr", [r"Cohort & $n$ & F2P (\%) & P2P (\%) & Strict (\%; count) \\"], lines)
    labels = {"tool_calls": "Tool calls", "chat_send_attempts": "Colleague messages",
              "distinct_colleague_recipients_attempted": "Distinct colleagues contacted", "agent_wall_hours": "Wall-clock hours"}
    lines = []
    for field, label in labels.items():
        d = s["effort"][field]
        fmt = (lambda v: f"{v:.2f}") if field == "agent_wall_hours" else (lambda v: f"{v:g}")
        lines.append(f"{label} & {d['n']} & {fmt(d['median'])} & [{fmt(d['p25'])}, {fmt(d['p75'])}] \\\\")
    tab("table_observed_effort.tex", "lrrl", [r"Measure & $n$ & Median & IQR [P25, P75] \\"], lines)
    tab("table_observed_ask.tex", "@{}lrrrrrr@{}",
        [r"& Ask rate & Targeting & Gain/Q & Follow-thr. & Redundancy & Unread \\"], rows["ask"].split("\n"))
    tab("table_observed_attrib.tex", "@{}lrrrrr@{}",
        [r"& \multicolumn{4}{c}{Share of unresolved F2P nodes (\%)} & \\", r"\cmidrule(lr){2-5}",
         r"Model & Discovery & Ask & Read & Implement & Unresolved \\"],
        [rows["attrib"].rsplit("&", 1)[0].rstrip() + r" \\"])
    tab("table_observed_strata.tex", "@{}llrrrr@{}",
        [r"Axis & Stratum & $n$ & F2P (\%) & Strict & Disclosed (\%) \\"], rows["strata"].split("\n"))
    if s.get("dimensions"):
        lines = []
        for d, label in DIM_LABELS.items():
            v = s["dimensions"][d]
            lines.append(" & ".join([label, str(v["rated_n"])] + [str(v["scores"][str(k)]) for k in range(4)] +
                                    [str(v["unrated_n"])]) + r" \\")
        tab("table_observed_dimensions.tex", "lrrrrrr", [r"Dimension & Rated $n$ & 0 & 1 & 2 & 3 & Unrated \\"], lines)


def main():
    cfg = config()
    s = json.loads((cfg.out / "statistics.json").read_text())
    model = cfg.model or s.get("model") or "model"
    rows = latex(s, model)
    pr = [f"% paper_rows.tex for {model} -- generated by cowork-model-report-skill (do not edit by hand).",
          "% Paste each row into the table named in the comment; \\tbd cells need runs this campaign does not have",
          "% (Oracle-Spec, seeds, tokens, expert agreement). See references/paper_mapping.md.", "",
          "% --- Table~\\ref{tab:main} (content/6_Results.tex): CoWork F2P, Strict(%) ---", rows["main"], "",
          "% --- Table~\\ref{tab:cost}: CoWork wall-clock (median minutes), tool calls (median) ---", rows["cost"], "",
          "% --- Table~\\ref{tab:attrib}: Discovery, Ask, Read, Implement (%), Unresolved nodes, Agreement ---",
          rows["attrib"], "",
          "% --- tables/table_observed_ask.tex (Table~\\ref{tab:ask}): model row + Spearman row ---", rows["ask"], "",
          "% --- tables/table_observed_strata.tex (Table~\\ref{tab:strata}) body ---", rows["strata"], ""]
    (cfg.out / "paper_rows.tex").write_text("\n".join(pr))
    write_tables(s, model, rows, cfg.out / "tables")
    env = cfg.env()
    env["MPLCONFIGDIR"] = str(cfg.out / ".cache" / "matplotlib")
    r = subprocess.run([sys.executable, str(HERE / "figures" / "model_figures.py"), "--out", str(cfg.out),
                        "--model", model], env=env, capture_output=True, text=True)
    if r.returncode:
        print(r.stderr[-3000:])
        raise SystemExit("figure generation failed")
    figs = json.loads(r.stdout.strip().splitlines()[-1])["figures"]
    tpl = jinja2.Environment(loader=jinja2.FileSystemLoader(str(HERE.parent / "templates")),
                             undefined=jinja2.StrictUndefined, trim_blocks=True, lstrip_blocks=True,
                             keep_trailing_newline=True)
    tpl.filters.update(f1=f1, f2=f2, rho=rho, pct0=pct0, num=num)
    md = tpl.get_template("report.md.j2").render(s=s, model=model, figures=[Path(f).name for f in figs],
                                                 rows=rows, dim_labels=DIM_LABELS, strata=STRATA)
    (cfg.out / "report.md").write_text(md)
    print(json.dumps({"report": str(cfg.out / "report.md"), "paper_rows": str(cfg.out / "paper_rows.tex"),
                      "figures": figs}))


if __name__ == "__main__":
    main()
